version: '3.8'

services:
    pgsql:
        image: postgres:12.4-alpine
        container_name: IntaVisionTest
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=123qwe
            - POSTGRES_DB=IntaVisionTest
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./docker/db:/var/lib/postgresql/data/pgdata